---
# tasks file for ldap-auth-client

- name: set debconf variables
  debconf: >
    name=ldap-auth-config
    question="ldap-auth-config/{{ item.key }}"
    vtype="{{ item.value.type }}"
    value="{{ item.value.value }}"
  with_dict: "{{ ldap_auth_config }}"
  register: ldap_debconf

- name: install libnss-ldap
  apt: pkg=libnss-ldap state=present
  register: ldap_install

- name: install libpam-ldap
  apt: pkg=libpam-ldap state=present
  register: ldap_install

- name: install ldap-utils
  apt: pkg=ldap-utils state=present
  register: ldap_install

- name: install nscd
  apt: pkg=nscd state=present
  when: ldap_nscd

- name: add ldap to passwd in nss file
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^passwd'
    line: 'passwd:         compat ldap'

- name: add ldap to group in nss file
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^group'
    line: 'group:          compat ldap'

- name: add ldap to shadow in nss file
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^shadow'
    line: 'shadow:         compat ldap'

- name: add auto create home directory to PAM
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session required        pam_mkhomedir.so skel=/etc/skel umask=077'

- name: Restart nscd service
  service:
    name: nscd
    state: restarted